### ISSUE TITLE
How to make pdf.js work in Deno

### ISSUE THREAD

**Issue by Leokuma** [takker99/deno-pdfjs-dist-types#1]
こんにちは！

Did you manage to make pdfjs work in Deno? I've been trying, but no luck so far. I'm trying to use the web build.

ありがとうございます。

**Comment by takker99** [comment]
Hello,Leokuma!

Unfortunately, I failed to run pdfjs in Deno. I faced 3 problems and two ones  (not provided ESM officially, not launching web worker) were resolved, but the last one (inject [deno-canvas](https://github.com/DjDeveloperr/deno-canvas) as an alternative to `<canvas>`) couldn't be resolved due to calling `document.createElement("canvas")` in pdfjs.

However, It is a year ago I tried doing this. Through the year Deno have great abilities such as npm compability.
Deno may run pdfjs now.

**Comment by takker99** [comment]
I wrote the survey in [this page](https://scrapbox.io/takker/Denoでpdfjsを使う).
But it just a scrap and be written in Japanese, so I think you can't read it...

I'll write it in English in my spare time.

**Comment by Leokuma** [comment]
ありがとうございます！

日本語を勉強しています。お父さんは日本人です。But no, I can't read your article 😭.

I gave up on using pdfjs in Deno. I decided to change my approach. I just needed to extract text from PDFs, so I installed `pdftotext` and I run it from inside Deno as a standalone process.

Anyway, thank you so much for your attention 👍.
